stages:
    - build
    - deploy

# This file is a template, and might need editing before it works on your project.
build-staging-image:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    # - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    # - docker push "$CI_REGISTRY_IMAGE"
    - echo 'CI/CD start'
  only:
    - master

deploy-staging-image:
  image: ubuntu:20.04
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt update -y && apt install openssh-client rsync sshpass -y )'
    - eval $(ssh-agent -s)
  script:
    - echo 'Send docker-compose to server'
#    - rsync --verbose --no-perms --chmod=D0700,F0700 --rsh="sshpass -e ssh -o StrictHostKeyChecking=no" ./production.yaml $SSH_ACNL_USER@$SSH_ACNL_SERVER:/home/$SSH_ACNL_USER/deploy/docker-compose.yaml
  only:
    - master

# docker-build:
#   # Official docker image.
#   image: docker:latest
#   stage: build
#   services:
#     - docker:dind
#   before_script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#   script:
#     - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
#     - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
#   except:
#     - master
