# Generated by Django 2.2.5 on 2019-09-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0, verbose_name='position')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
                ('season', models.CharField(choices=[('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn')], default='winter', max_length=7, verbose_name='season')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0, verbose_name='position')),
                ('show', models.BooleanField(default=False, verbose_name='show')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('desc', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0, verbose_name='position')),
                ('pic', models.ImageField(upload_to='units', verbose_name='image')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('rarity', models.IntegerField(choices=[(1, 'Very Common'), (2, 'Common'), (3, 'Rare'), (4, 'Vary Rare')], default=1, verbose_name='rarity')),
                ('desc', models.TextField(verbose_name='description')),
                ('loc', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('island', models.BooleanField(default=False, verbose_name='island')),
                ('shadow', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('fin', 'Fin'), ('narrow', 'Narrow')], max_length=7, verbose_name='shadow')),
                ('price', models.IntegerField(default=100, verbose_name='price')),
                ('str_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('months', models.ManyToManyField(to='encyclopedia.Month')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.Section')),
            ],
        ),
    ]
