# Generated by Django 2.2.5 on 2019-09-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='months',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
