# Generated by Django 2.2.5 on 2019-09-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0004_auto_20190927_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='season_old',
        ),
    ]
