# Generated by Django 2.2.5 on 2019-10-04 13:18

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0005_remove_month_season_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='color',
            field=models.CharField(blank=True, help_text='HSL Color. Example: 120,50%,50%', max_length=100, null=True, validators=[django.core.validators.RegexValidator(re.compile('^(\\d+),\\s*([\\d.]+)%,\\s*([\\d.]+)%\\Z'), "Enter a valid 'HSL' consisting of hue 0-360, saturation 0%-100%, lightness 0%-100%", 'invalid')], verbose_name='color'),
        ),
    ]
