version: '3'

volumes:
  dbdata:
  media:
  static:
  logs:

services:
  postgres:
    image: "postgres:11"
    container_name: "acnl_postgres"
    ports:
      - "54320:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  django:
    container_name: "acnl_django"
    build:
      context: .
      dockerfile: ./acnl_django/Dockerfile
    command: bash ./acnl_django/prod-run.bash
    volumes:
      - .:/code
      - media_files:/var/www/django/acnl/media
      - static_files:/var/www/django/acnl/static
      - logs:/var/www/django/acnl/logs
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  nginx:
    container_name: "acnl_nginx"
    build:
      context: .
      dockerfile: ./acnl_nginx/Dockerfile
    volumes:
      - .:/code
      - media_files:/var/www/django/acnl/media
      - static_files:/var/www/django/acnl/static
      - logs:/var/www/django/acnl/logs
