# Generated by Django 2.2.28 on 2024-09-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='show',
            field=models.BooleanField(db_index=True, default=False, verbose_name='show'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
