# Generated by Django 2.2.28 on 2024-09-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0006_auto_20191004_1618'),
        ('creatures', '0002_auto_20240901_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('position', models.IntegerField(default=0, verbose_name='position')),
                ('picture', models.ImageField(upload_to='animals', verbose_name='image')),
                ('price', models.IntegerField(default=100, verbose_name='price')),
                ('inhabit', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('is_island', models.BooleanField(default=False, verbose_name='Available on island')),
                ('time_appearance', models.TimeField(verbose_name='appearance time')),
                ('time_disappearance', models.TimeField(verbose_name='disappearance time')),
                ('bug_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creatures.Bug')),
                ('months', models.ManyToManyField(to='encyclopedia.Month')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creatures.Rarity')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creatures.Section')),
                ('shadow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creatures.Shadow')),
            ],
            options={
                'verbose_name': 'animal',
                'verbose_name_plural': 'animals',
            },
        ),
    ]
